image: openjdk:8-jdk
before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle assemble
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle check
