contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://nishtahir.gitlab.io/linkbait/"
title         = "An extensible bot framework with support for plugins"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"
