/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'nish' at '4/19/16 10:35 PM' with Gradle 2.11
 *
 * @author nish, @date 4/19/16 10:35 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
