/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fotty' at '2/8/16 3:36 AM' with Gradle 2.10
 *
 * @author fotty, @date 2/8/16 3:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
